// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: abstractMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest is a publish request.
type AbstractMessageProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageTypeProto `protobuf:"varint,1,opt,name=messageType,proto3,enum=io.seata.protocol.protobuf.MessageTypeProto" json:"messageType,omitempty"`
}

func (x *AbstractMessageProto) Reset() {
	*x = AbstractMessageProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_abstractMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbstractMessageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbstractMessageProto) ProtoMessage() {}

func (x *AbstractMessageProto) ProtoReflect() protoreflect.Message {
	mi := &file_abstractMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbstractMessageProto.ProtoReflect.Descriptor instead.
func (*AbstractMessageProto) Descriptor() ([]byte, []int) {
	return file_abstractMessage_proto_rawDescGZIP(), []int{0}
}

func (x *AbstractMessageProto) GetMessageType() MessageTypeProto {
	if x != nil {
		return x.MessageType
	}
	return MessageTypeProto_TYPE_GLOBAL_PRESERVED
}

var File_abstractMessage_proto protoreflect.FileDescriptor

var file_abstractMessage_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x69, 0x6f, 0x2e, 0x73, 0x65, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x1a, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x14, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4e,
	0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x69, 0x6f, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x40,
	0x0a, 0x26, 0x69, 0x6f, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0f, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x01, 0x5a, 0x03, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_abstractMessage_proto_rawDescOnce sync.Once
	file_abstractMessage_proto_rawDescData = file_abstractMessage_proto_rawDesc
)

func file_abstractMessage_proto_rawDescGZIP() []byte {
	file_abstractMessage_proto_rawDescOnce.Do(func() {
		file_abstractMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_abstractMessage_proto_rawDescData)
	})
	return file_abstractMessage_proto_rawDescData
}

var file_abstractMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_abstractMessage_proto_goTypes = []interface{}{
	(*AbstractMessageProto)(nil), // 0: io.seata.protocol.protobuf.AbstractMessageProto
	(MessageTypeProto)(0),        // 1: io.seata.protocol.protobuf.MessageTypeProto
}
var file_abstractMessage_proto_depIdxs = []int32{
	1, // 0: io.seata.protocol.protobuf.AbstractMessageProto.messageType:type_name -> io.seata.protocol.protobuf.MessageTypeProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_abstractMessage_proto_init() }
func file_abstractMessage_proto_init() {
	if File_abstractMessage_proto != nil {
		return
	}
	file_messageType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_abstractMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbstractMessageProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_abstractMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_abstractMessage_proto_goTypes,
		DependencyIndexes: file_abstractMessage_proto_depIdxs,
		MessageInfos:      file_abstractMessage_proto_msgTypes,
	}.Build()
	File_abstractMessage_proto = out.File
	file_abstractMessage_proto_rawDesc = nil
	file_abstractMessage_proto_goTypes = nil
	file_abstractMessage_proto_depIdxs = nil
}
