// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: testMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestTimeoutRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbstractIdentifyRequest *AbstractIdentifyRequestProto `protobuf:"bytes,1,opt,name=abstractIdentifyRequest,proto3" json:"abstractIdentifyRequest,omitempty"`
	SleepTime               uint32                        `protobuf:"varint,2,opt,name=sleepTime,proto3" json:"sleepTime,omitempty"`
}

func (x *TestTimeoutRequestProto) Reset() {
	*x = TestTimeoutRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTimeoutRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTimeoutRequestProto) ProtoMessage() {}

func (x *TestTimeoutRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_testMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTimeoutRequestProto.ProtoReflect.Descriptor instead.
func (*TestTimeoutRequestProto) Descriptor() ([]byte, []int) {
	return file_testMessage_proto_rawDescGZIP(), []int{0}
}

func (x *TestTimeoutRequestProto) GetAbstractIdentifyRequest() *AbstractIdentifyRequestProto {
	if x != nil {
		return x.AbstractIdentifyRequest
	}
	return nil
}

func (x *TestTimeoutRequestProto) GetSleepTime() uint32 {
	if x != nil {
		return x.SleepTime
	}
	return 0
}

type TestTimeoutResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbstractIdentifyResponse *AbstractIdentifyResponseProto `protobuf:"bytes,1,opt,name=abstractIdentifyResponse,proto3" json:"abstractIdentifyResponse,omitempty"`
}

func (x *TestTimeoutResponseProto) Reset() {
	*x = TestTimeoutResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTimeoutResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTimeoutResponseProto) ProtoMessage() {}

func (x *TestTimeoutResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_testMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTimeoutResponseProto.ProtoReflect.Descriptor instead.
func (*TestTimeoutResponseProto) Descriptor() ([]byte, []int) {
	return file_testMessage_proto_rawDescGZIP(), []int{1}
}

func (x *TestTimeoutResponseProto) GetAbstractIdentifyResponse() *AbstractIdentifyResponseProto {
	if x != nil {
		return x.AbstractIdentifyResponse
	}
	return nil
}

var File_testMessage_proto protoreflect.FileDescriptor

var file_testMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x69, 0x6f, 0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a,
	0x1d, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab,
	0x01, 0x0a, 0x17, 0x54, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x72, 0x0a, 0x17, 0x61, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x69, 0x6f,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x17, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x91, 0x01, 0x0a,
	0x18, 0x54, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x75, 0x0a, 0x18, 0x61, 0x62, 0x73,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x69, 0x6f,
	0x2e, 0x73, 0x65, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x18, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testMessage_proto_rawDescOnce sync.Once
	file_testMessage_proto_rawDescData = file_testMessage_proto_rawDesc
)

func file_testMessage_proto_rawDescGZIP() []byte {
	file_testMessage_proto_rawDescOnce.Do(func() {
		file_testMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_testMessage_proto_rawDescData)
	})
	return file_testMessage_proto_rawDescData
}

var file_testMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testMessage_proto_goTypes = []interface{}{
	(*TestTimeoutRequestProto)(nil),       // 0: io.seata.protocol.protobuf.TestTimeoutRequestProto
	(*TestTimeoutResponseProto)(nil),      // 1: io.seata.protocol.protobuf.TestTimeoutResponseProto
	(*AbstractIdentifyRequestProto)(nil),  // 2: io.seata.protocol.protobuf.AbstractIdentifyRequestProto
	(*AbstractIdentifyResponseProto)(nil), // 3: io.seata.protocol.protobuf.AbstractIdentifyResponseProto
}
var file_testMessage_proto_depIdxs = []int32{
	2, // 0: io.seata.protocol.protobuf.TestTimeoutRequestProto.abstractIdentifyRequest:type_name -> io.seata.protocol.protobuf.AbstractIdentifyRequestProto
	3, // 1: io.seata.protocol.protobuf.TestTimeoutResponseProto.abstractIdentifyResponse:type_name -> io.seata.protocol.protobuf.AbstractIdentifyResponseProto
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_testMessage_proto_init() }
func file_testMessage_proto_init() {
	if File_testMessage_proto != nil {
		return
	}
	file_abstractIdentifyRequest_proto_init()
	file_abstractIdentifyResponse_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_testMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTimeoutRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTimeoutResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testMessage_proto_goTypes,
		DependencyIndexes: file_testMessage_proto_depIdxs,
		MessageInfos:      file_testMessage_proto_msgTypes,
	}.Build()
	File_testMessage_proto = out.File
	file_testMessage_proto_rawDesc = nil
	file_testMessage_proto_goTypes = nil
	file_testMessage_proto_depIdxs = nil
}
